name: ${project.name}
description: ${project.description}
author: Fahrenheit451|Capri205
version: ${project.version}
api-version: ${api-version}
website: ${project.url}
main: net.obmc.${project.name}.${project.name}
commands:
  mobwarn:
    description: OBMobWarn command.
    usage: Type /mobwarn for a list of commands